# Generated by Django 4.2.4 on 2023-08-20 14:33

import apps.auth_r.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_r", "0002_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SELLER", "Seller"),
                    ("BUYER", "Buyer"),
                    ("ORGANIZATION", "Organization"),
                ],
                default="SELLER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=apps.auth_r.models.generate_username_from_datetime,
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
            ),
        ),
    ]
