# Generated by Django 4.2.4 on 2023-08-27 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="buyer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="job",
        ),
        migrations.AlterField(
            model_name="job",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="category.category",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
